
layout(rgba32f, binding = 0) uniform image2D img_output;
layout(rgba32f, binding = 1) uniform image2D img_input;

uniform float weight;

void main() 
{
	ivec2 coords = ivec2(gl_GlobalInvocationID);
	vec4 in_pixel = imageLoad(img_input, coords);
	vec4 out_pixel = imageLoad(img_output, coords);
	out_pixel = vec4(out_pixel.x + in_pixel.x * weight, out_pixel.y + in_pixel.y * weight, out_pixel.z + in_pixel.z * weight, out_pixel.w + in_pixel.w * weight);
	imageStore(img_output, coords, out_pixel);
}